# Generated by Django 2.2.12 on 2022-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=122)),
                ('standard', models.CharField(max_length=122)),
                ('writer', models.CharField(max_length=122)),
                ('course', models.CharField(max_length=122)),
            ],
        ),
    ]
