# Generated by Django 2.2.12 on 2022-02-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static/images/'),
        ),
    ]
