# Generated by Django 2.2.12 on 2022-03-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220308_0634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MY',
        ),
    ]
