# Generated by Django 2.2.12 on 2022-03-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_my'),
    ]

    operations = [
        migrations.CreateModel(
            name='MY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=122)),
            ],
        ),
    ]
