# Generated by Django 2.2.12 on 2022-03-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_jeans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Jeans',
        ),
        migrations.DeleteModel(
            name='MY',
        ),
        migrations.DeleteModel(
            name='My_home',
        ),
    ]
