# Generated by Django 2.2.12 on 2022-04-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220314_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(max_length=200)),
            ],
            options={
                'db_table': 'analytic',
            },
        ),
    ]
