# Generated by Django 2.2.12 on 2022-04-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_analytic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analytic',
            table='users',
        ),
    ]
