# Generated by Django 2.2.12 on 2022-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220407_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='cats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cats',
            },
        ),
        migrations.DeleteModel(
            name='analytic',
        ),
    ]
